version: '3'

services:
  front:
    build: ./frontend
    container_name: front
    ports:
      - 8080:3000 # fwd to 8080 on the host machine
    environment:
      PUBLIC_PLACES_REST_API_URL: http://localhost:9090
  
  api:
    build: ./backend
    container_name: api
    ports:
      - 9090:80 # fwd to 9090 on the host machine